version: "3.3"

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    networks:
      - traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  repsysml:
    image: "cowjen01/repsys-demo:0.3.4"
    networks:
      - traefik_proxy
    command: "server --dataset-pkg datasets.ml20m"
    volumes:
      - ".repsys_checkpoints/ml20m:/app/.repsys_checkpoints"
      - "./checkpoints/ml20m:/app/checkpoints"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repsysml.rule=Host(`repsys-demo-1.kam.fit.cvut.cz`)"
      - "traefik.http.middlewares.repsysml-auth.basicauth.users=guest:$$apr1$$b5z3Xj8N$$sVQdCdctCFWsfUfFKf7sH/"
      - "traefik.http.routers.repsysml.middlewares=repsysml-auth"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

  repsysgb:
    image: "cowjen01/repsys-demo:0.3.4"
    networks:
      - traefik_proxy
    command: "server --dataset-pkg datasets.gb"
    volumes:
      - ".repsys_checkpoints/gb:/app/.repsys_checkpoints"
      - "./checkpoints/gb:/app/checkpoints"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repsysgb.rule=Host(`repsys-demo-2.kam.fit.cvut.cz`)"
      - "traefik.http.middlewares.repsysgb-auth.basicauth.users=guest:$$apr1$$b5z3Xj8N$$sVQdCdctCFWsfUfFKf7sH/"
      - "traefik.http.routers.repsysgb.middlewares=repsysgb-auth"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

  repsysmlbeta:
    image: "cowjen01/repsys-demo:latest"
    networks:
      - traefik_proxy
    command: "server --dataset-pkg datasets.ml20m"
    volumes:
      - ".repsys_checkpoints/ml20m:/app/.repsys_checkpoints"
      - "./checkpoints/ml20m:/app/checkpoints"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repsysmlbeta.rule=Host(`repsys-demo-3.kam.fit.cvut.cz`)"
      - "traefik.http.middlewares.repsysmlbeta-auth.basicauth.users=guest:$$apr1$$b5z3Xj8N$$sVQdCdctCFWsfUfFKf7sH/"
      - "traefik.http.routers.repsysmlbeta.middlewares=repsysmlbeta-auth"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
