version: "3.3"

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    networks:
      - traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  repsys:
    image: "cowjen01/repsys-ml:latest"
    networks:
      - traefik_proxy
    volumes:
      - ".repsys_checkpoints:/app/.repsys_checkpoints"
      - "./checkpoints:/app/checkpoints"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repsys.rule=Host(`repsys.localhost`)"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy: