version: "3.3"

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    networks:
      - traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.http.middlewares.repsys-auth.basicauth.users=guest:$$apr1$$b5z3Xj8N$$sVQdCdctCFWsfUfFKf7sH/"
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  repsysml:
    image: "cowjen01/repsys-demo:latest"
    networks:
      - traefik_proxy
    command: "server --dataset-pkg datasets.ml20m"
    volumes:
      - ".repsys_checkpoints/ml20m:/app/.repsys_checkpoints"
      - "./checkpoints/ml20m:/app/checkpoints"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.repsysml.rule=Host(`repsys-demo-1.kam.fit.cvut.cz`)"
      - "traefik.http.routers.repsysml.middlewares=repsys-auth"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

  repsysgb:
   image: "cowjen01/repsys-demo:latest"
    networks:
     - traefik_proxy
    command: "server --dataset-pkg datasets.gb"
    volumes:
     - ".repsys_checkpoints/gb:/app/.repsys_checkpoints"
     - "./checkpoints/gb:/app/checkpoints"
    labels:
     - "traefik.enable=true"
      - "traefik.http.routers.repsysgb.rule=Host(`repsys-demo-2.kam.fit.cvut.cz`)"
      - "traefik.http.routers.repsysgb.middlewares=repsys-auth"
      - "traefik.port=3001"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
